#include "types.h"

#include <fonts/mdi.h>

SMARTENUM_DEFINE(_GameCategory, GameCategory)

SMARTENUM_DEFINE(_GameStatus, GameStatus)
const GameStatusInfo game_status[1 + GameStatus_COUNT] = {
    // clang-format off
    [GameStatus_Normal] = {.color = {{0.95f, 0.95f, 0.95f, 1.0f}}, .icon = mdi_lightning_bolt_circle},
    [GameStatus_Completed] = {.color = {{0.0f, 0.87f, 0.0f, 1.0f}}, .icon = mdi_checkbox_marked_circle},
    [GameStatus_OnHold] = {.color = {{0.0f, 0.5f, 0.95f, 1.0f}}, .icon = mdi_pause_circle},
    [GameStatus_Abandoned] = {.color = {{0.87f, 0.2f, 0.2f, 1.0f}}, .icon = mdi_close_circle},
    [GameStatus_Unchecked] = {.color = {{0.5f, 0.5f, 0.5f, 1.0f}}, .icon = mdi_alert_circle},
    [GameStatus_Custom] = {.color = {{0.95f, 0.5f, 0.0f, 1.0f}}, .icon = mdi_dots_horizontal_circle},
    // clang-format on
};

SMARTENUM_DEFINE(_GameTag, GameTag)
const GameTagInfo game_tag[1 + GameTag_COUNT] = {
    [GameTag_2dGame] = {.text = "2d game"},
    [GameTag_2dcg] = {.text = "2dcg"},
    [GameTag_3dGame] = {.text = "3d game"},
    [GameTag_3dcg] = {.text = "3dcg"},
    [GameTag_Adventure] = {.text = "adventure"},
    [GameTag_Ahegao] = {.text = "ahegao"},
    [GameTag_AiCg] = {.text = "ai cg"},
    [GameTag_AnalSex] = {.text = "anal sex"},
    [GameTag_Animated] = {.text = "animated"},
    [GameTag_AssetAddon] = {.text = "asset-addon"},
    [GameTag_AssetAiShoujo] = {.text = "asset-ai-shoujo"},
    [GameTag_AssetAnimal] = {.text = "asset-animal"},
    [GameTag_AssetAnimation] = {.text = "asset-animation"},
    [GameTag_AssetAudio] = {.text = "asset-audio"},
    [GameTag_AssetBundle] = {.text = "asset-bundle"},
    [GameTag_AssetCharacter] = {.text = "asset-character"},
    [GameTag_AssetClothing] = {.text = "asset-clothing"},
    [GameTag_AssetDazGen1] = {.text = "asset-daz-gen1"},
    [GameTag_AssetDazGen2] = {.text = "asset-daz-gen2"},
    [GameTag_AssetDazGen3] = {.text = "asset-daz-gen3"},
    [GameTag_AssetDazGen8] = {.text = "asset-daz-gen8"},
    [GameTag_AssetDazGen81] = {.text = "asset-daz-gen81"},
    [GameTag_AssetDazGen9] = {.text = "asset-daz-gen9"},
    [GameTag_AssetDazM4] = {.text = "asset-daz-m4"},
    [GameTag_AssetDazV4] = {.text = "asset-daz-v4"},
    [GameTag_AssetEnvironment] = {.text = "asset-environment"},
    [GameTag_AssetExpression] = {.text = "asset-expression"},
    [GameTag_AssetFemale] = {.text = "asset-female"},
    [GameTag_AssetHair] = {.text = "asset-hair"},
    [GameTag_AssetHdri] = {.text = "asset-hdri"},
    [GameTag_AssetHoneySelect] = {.text = "asset-honey-select"},
    [GameTag_AssetHoneySelect2] = {.text = "asset-honey-select2"},
    [GameTag_AssetKoikatu] = {.text = "asset-koikatu"},
    [GameTag_AssetLight] = {.text = "asset-light"},
    [GameTag_AssetMale] = {.text = "asset-male"},
    [GameTag_AssetMorph] = {.text = "asset-morph"},
    [GameTag_AssetNonbinary] = {.text = "asset-nonbinary"},
    [GameTag_AssetPlayhome] = {.text = "asset-playhome"},
    [GameTag_AssetPlugin] = {.text = "asset-plugin"},
    [GameTag_AssetPose] = {.text = "asset-pose"},
    [GameTag_AssetProp] = {.text = "asset-prop"},
    [GameTag_AssetScene] = {.text = "asset-scene"},
    [GameTag_AssetScript] = {.text = "asset-script"},
    [GameTag_AssetShader] = {.text = "asset-shader"},
    [GameTag_AssetTexture] = {.text = "asset-texture"},
    [GameTag_AssetUtility] = {.text = "asset-utility"},
    [GameTag_AssetVehicle] = {.text = "asset-vehicle"},
    [GameTag_Bdsm] = {.text = "bdsm"},
    [GameTag_Bestiality] = {.text = "bestiality"},
    [GameTag_BigAss] = {.text = "big ass"},
    [GameTag_BigTits] = {.text = "big tits"},
    [GameTag_Blackmail] = {.text = "blackmail"},
    [GameTag_Bukkake] = {.text = "bukkake"},
    [GameTag_Censored] = {.text = "censored"},
    [GameTag_CharacterCreation] = {.text = "character creation"},
    [GameTag_Cheating] = {.text = "cheating"},
    [GameTag_Combat] = {.text = "combat"},
    [GameTag_Corruption] = {.text = "corruption"},
    [GameTag_Cosplay] = {.text = "cosplay"},
    [GameTag_Creampie] = {.text = "creampie"},
    [GameTag_DatingSim] = {.text = "dating sim"},
    [GameTag_Dilf] = {.text = "dilf"},
    [GameTag_Drugs] = {.text = "drugs"},
    [GameTag_DystopianSetting] = {.text = "dystopian setting"},
    [GameTag_Exhibitionism] = {.text = "exhibitionism"},
    [GameTag_Fantasy] = {.text = "fantasy"},
    [GameTag_FemaleProtagonist] = {.text = "female protagonist"},
    [GameTag_Femaledomination] = {.text = "female domination"},
    [GameTag_Footjob] = {.text = "footjob"},
    [GameTag_Furry] = {.text = "furry"},
    [GameTag_FutaTrans] = {.text = "futa/trans"},
    [GameTag_FutaTransProtagonist] = {.text = "futa/trans protagonist"},
    [GameTag_Gay] = {.text = "gay"},
    [GameTag_GraphicViolence] = {.text = "graphic violence"},
    [GameTag_Groping] = {.text = "groping"},
    [GameTag_GroupSex] = {.text = "group sex"},
    [GameTag_Handjob] = {.text = "handjob"},
    [GameTag_Harem] = {.text = "harem"},
    [GameTag_Horror] = {.text = "horror"},
    [GameTag_Humiliation] = {.text = "humiliation"},
    [GameTag_Humor] = {.text = "humor"},
    [GameTag_Incest] = {.text = "incest"},
    [GameTag_InternalView] = {.text = "internal view"},
    [GameTag_Interracial] = {.text = "interracial"},
    [GameTag_JapaneseGame] = {.text = "japanese game"},
    [GameTag_KineticNovel] = {.text = "kinetic novel"},
    [GameTag_Lactation] = {.text = "lactation"},
    [GameTag_Lesbian] = {.text = "lesbian"},
    [GameTag_Loli] = {.text = "loli"},
    [GameTag_MaleProtagonist] = {.text = "male protagonist"},
    [GameTag_Maledomination] = {.text = "male domination"},
    [GameTag_Management] = {.text = "management"},
    [GameTag_Masturbation] = {.text = "masturbation"},
    [GameTag_Milf] = {.text = "milf"},
    [GameTag_MindControl] = {.text = "mind control"},
    [GameTag_MobileGame] = {.text = "mobile game"},
    [GameTag_Monster] = {.text = "monster"},
    [GameTag_MonsterGirl] = {.text = "monster girl"},
    [GameTag_MultipleEndings] = {.text = "multiple endings"},
    [GameTag_MultiplePenetration] = {.text = "multiple penetration"},
    [GameTag_MultipleProtagonist] = {.text = "multiple protagonist"},
    [GameTag_Necrophilia] = {.text = "necrophilia"},
    [GameTag_NoSexualContent] = {.text = "no sexual content"},
    [GameTag_Ntr] = {.text = "netorare"},
    [GameTag_OralSex] = {.text = "oral sex"},
    [GameTag_Paranormal] = {.text = "paranormal"},
    [GameTag_Parody] = {.text = "parody"},
    [GameTag_Platformer] = {.text = "platformer"},
    [GameTag_PointClick] = {.text = "point & click"},
    [GameTag_Possession] = {.text = "possession"},
    [GameTag_Pov] = {.text = "pov"},
    [GameTag_Pregnancy] = {.text = "pregnancy"},
    [GameTag_Prostitution] = {.text = "prostitution"},
    [GameTag_Puzzle] = {.text = "puzzle"},
    [GameTag_Rape] = {.text = "rape"},
    [GameTag_RealPorn] = {.text = "real porn"},
    [GameTag_Religion] = {.text = "religion"},
    [GameTag_Romance] = {.text = "romance"},
    [GameTag_Rpg] = {.text = "rpg"},
    [GameTag_Sandbox] = {.text = "sandbox"},
    [GameTag_Scat] = {.text = "scat"},
    [GameTag_SchoolSetting] = {.text = "school setting"},
    [GameTag_SciFi] = {.text = "sci-fi"},
    [GameTag_SexToys] = {.text = "sex toys"},
    [GameTag_SexualHarassment] = {.text = "sexual harassment"},
    [GameTag_Shooter] = {.text = "shooter"},
    [GameTag_Shota] = {.text = "shota"},
    [GameTag_SideScroller] = {.text = "side-scroller"},
    [GameTag_Simulator] = {.text = "simulator"},
    [GameTag_Sissification] = {.text = "sissification"},
    [GameTag_Slave] = {.text = "slave"},
    [GameTag_SleepSex] = {.text = "sleep sex"},
    [GameTag_Spanking] = {.text = "spanking"},
    [GameTag_Strategy] = {.text = "strategy"},
    [GameTag_Stripping] = {.text = "stripping"},
    [GameTag_Superpowers] = {.text = "superpowers"},
    [GameTag_Swinging] = {.text = "swinging"},
    [GameTag_Teasing] = {.text = "teasing"},
    [GameTag_Tentacles] = {.text = "tentacles"},
    [GameTag_TextBased] = {.text = "text based"},
    [GameTag_Titfuck] = {.text = "titfuck"},
    [GameTag_Trainer] = {.text = "trainer"},
    [GameTag_Transformation] = {.text = "transformation"},
    [GameTag_Trap] = {.text = "trap"},
    [GameTag_TurnBasedCombat] = {.text = "turn based combat"},
    [GameTag_Twins] = {.text = "twins"},
    [GameTag_Urination] = {.text = "urination"},
    [GameTag_VaginalSex] = {.text = "vaginal sex"},
    [GameTag_Virgin] = {.text = "virgin"},
    [GameTag_VirtualReality] = {.text = "virtual reality"},
    [GameTag_Voiced] = {.text = "voiced"},
    [GameTag_Vore] = {.text = "vore"},
    [GameTag_Voyeurism] = {.text = "voyeurism"},
};

SMARTENUM_DEFINE(_GameTimelineEventType, GameTimelineEventType)
const GameTimelineEventTypeInfo game_timeline_event_type[1 + GameTimelineEventType_COUNT] = {
    // FIXME: update format specifiers for sprintf
    [GameTimelineEventType_Added] =
        {
            .display = "Added",
            .icon = mdi_alert_decagram,
            .args_min = 0,
            .template = "Added to the library",
        },
    [GameTimelineEventType_Launched] =
        {
            .display = "Launched",
            .icon = mdi_play,
            .args_min = 1,
            .template = "Launched {}",
        },
    [GameTimelineEventType_Finished] =
        {
            .display = "Finished",
            .icon = mdi_flag_checkered,
            .args_min = 1,
            .template = "Finished {}",
        },
    [GameTimelineEventType_Installed] =
        {
            .display = "Installed",
            .icon = mdi_download,
            .args_min = 1,
            .template = "Installed {}",
        },
    [GameTimelineEventType_ChangedName] =
        {
            .display = "Changed name",
            .icon = mdi_spellcheck,
            .args_min = 2,
            .template = "Name changed from \"{}\" to \"{}\"",
        },
    [GameTimelineEventType_ChangedStatus] =
        {
            .display = "Changed status",
            .icon = mdi_lightning_bolt,
            .args_min = 2,
            .template = "Status changed from \"{}\" to \"{}\"",
        },
    [GameTimelineEventType_ChangedVersion] =
        {
            .display = "Changed version",
            .icon = mdi_star,
            .args_min = 2,
            .template = "Version changed from \"{}\" to \"{}\"",
        },
    [GameTimelineEventType_ChangedDeveloper] =
        {
            .display = "Changed developer",
            .icon = mdi_account,
            .args_min = 2,
            .template = "Developer changed from \"{}\" to \"{}\"",
        },
    [GameTimelineEventType_ChangedType] =
        {
            .display = "Changed type",
            .icon = mdi_shape,
            .args_min = 2,
            .template = "Type changed from \"{}\" to \"{}\"",
        },
    [GameTimelineEventType_TagsAdded] =
        {
            .display = "Tags added",
            .icon = mdi_tag_plus,
            .args_min = 1,
            .template = "Tags were added: {}",
        },
    [GameTimelineEventType_TagsRemoved] =
        {
            .display = "Tags removed",
            .icon = mdi_tag_minus,
            .args_min = 1,
            .template = "Tags were removed: {}",
        },
    [GameTimelineEventType_ScoreIncreased] =
        {
            .display = "Score increased",
            .icon = mdi_thumb_up,
            .args_min = 4,
            .template = "Forum score increased from {} ({}) to {} ({})",
        },
    [GameTimelineEventType_ScoreDecreased] =
        {
            .display = "Score decreased",
            .icon = mdi_thumb_down,
            .args_min = 4,
            .template = "Forum score decreased from {} ({}) to {} ({})",
        },
    [GameTimelineEventType_RecheckExpired] =
        {
            .display = "Recheck expired",
            .icon = mdi_timer_sync,
            .args_min = 1,
            .template =
                "Forcefully performed a full recheck because game has remained idle for {} day(s)",
        },
    [GameTimelineEventType_RecheckUserReq] =
        {
            .display = "Recheck requested",
            .icon = mdi_reload_alert,
            .args_min = 0,
            .template = "Forcefully performed a full recheck requested by user",
        },
};

SMARTENUM_DEFINE(_GameType, GameType)
const GameTypeInfo game_type[1 + GameType_COUNT] = {
    // clang-format off
    [GameType_ADRIFT] = {.color = {{0.129f, 0.588f, 0.953f, 1.0f}}, .category = GameCategory_Games},
    [GameType_Flash] = {.color = {{0.38f, 0.38f, 0.38f, 1.0f}}, .category = GameCategory_Games},
    [GameType_HTML] = {.color = {{0.408f, 0.624f, 0.22f, 1.0f}}, .category = GameCategory_Games},
    [GameType_Java] = {.color = {{0.322f, 0.651f, 0.69f, 1.0f}}, .category = GameCategory_Games},
    [GameType_Others] = {.color = {{0.545f, 0.765f, 0.29f, 1.0f}}, .category = GameCategory_Games},
    [GameType_QSP] = {.color = {{0.827f, 0.184f, 0.184f, 1.0f}}, .category = GameCategory_Games},
    [GameType_RAGS] = {.color = {{1.0f, 0.596f, 0.0f, 1.0f}}, .category = GameCategory_Games},
    [GameType_RenPy] = {.color = {{0.69f, 0.412f, 0.91f, 1.0f}}, .category = GameCategory_Games},
    [GameType_RPGM] = {.color = {{0.129f, 0.588f, 0.953f, 1.0f}}, .category = GameCategory_Games},
    [GameType_Tads] = {.color = {{0.129f, 0.588f, 0.953f, 1.0f}}, .category = GameCategory_Games},
    [GameType_Unity] = {.color = {{0.996f, 0.349f, 0.004f, 1.0f}}, .category = GameCategory_Games},
    [GameType_UnrealEng] = {.color = {{0.051f, 0.278f, 0.631f, 1.0f}}, .category = GameCategory_Games},
    [GameType_WebGL] = {.color = {{0.996f, 0.349f, 0.004f, 1.0f}}, .category = GameCategory_Games},
    [GameType_WolfRPG] = {.color = {{0.298f, 0.686f, 0.314f, 1.0f}}, .category = GameCategory_Games},
    [GameType_CG] = {.color = {{0.875f, 0.796f, 0.216f, 1.0f}}, .category = GameCategory_Media},
    [GameType_Collection] = {.color = {{0.38f, 0.38f, 0.38f, 1.0f}}, .category = GameCategory_Media},
    [GameType_Comics] = {.color = {{1.0f, 0.596f, 0.0f, 1.0f}}, .category = GameCategory_Media},
    [GameType_GIF] = {.color = {{0.012f, 0.663f, 0.957f, 1.0f}}, .category = GameCategory_Media},
    [GameType_Manga] = {.color = {{0.059f, 0.698f, 0.988f, 1.0f}}, .category = GameCategory_Media},
    [GameType_Pinup] = {.color = {{0.129f, 0.588f, 0.953f, 1.0f}}, .category = GameCategory_Media},
    [GameType_SiteRip] = {.color = {{0.545f, 0.765f, 0.29f, 1.0f}}, .category = GameCategory_Media},
    [GameType_Video] = {.color = {{1.0f, 0.596f, 0.0f, 1.0f}}, .category = GameCategory_Media},
    [GameType_CheatMod] = {.color = {{0.827f, 0.184f, 0.184f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Mod] = {.color = {{0.729f, 0.271f, 0.271f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_README] = {.color = {{0.863f, 0.078f, 0.235f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Request] = {.color = {{0.827f, 0.184f, 0.184f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Tool] = {.color = {{0.925f, 0.333f, 0.333f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Tutorial] = {.color = {{0.925f, 0.333f, 0.333f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Misc] = {.color = {{0.722f, 0.69f, 0.047f, 1.0f}}, .category = GameCategory_Misc},
    [GameType_Unchecked] = {.color = {{0.224f, 0.224f, 0.224f, 1.0f}}, .category = GameCategory_Misc},
    // clang-format on
};
